# Usa la imagen base de .NET SDK
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Usa la imagen base de .NET SDK para la compilación
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Parcial/Parcial.csproj", "Parcial/"]
RUN dotnet restore "Parcial/Parcial.csproj"
COPY . .
WORKDIR "/src/Parcial"
RUN dotnet build "Parcial.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Parcial.csproj" -c Release -o /app/publish

# Copia los archivos y realiza el despliegue
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Parcial.dll"]
